---
title: "Moncayo Notes First Meeting"
date: "April 10, 2018"
output: pdf_document
---

# Econ 381 Notes

- 10 Hours/week between Drew and I.

- Designing the class from scratch.

- Think about the base student who might have just barely got into BYUI

- Aim high but approach it through multiple steps. 

- Give them structure and hold their hand and give them more autonomy a long the way

# The Course

- Replacement for CS 101 introduction to python

- Goal is to prepare students for CS 241

- Books used by students Macro Economics Charles I. Jones

- Advanced Macroeconomics David Romer

# Topics

- 4 models

- Solow Model -> Romer Model (Long Run Growth, Cross Country Comparisons)
  - Half of Semester
  
- Keynsian Model

- Real Business Cycle Model Kidd Finland

# Week 1

- Foundations
  - Macro Concepts
  - Python
  
- Reading Quiz on the book
  
# Week 2

- Math Strengthing Review
  - Build Python Model
  
# Week 3

- Take data and put it into the model and run simulations

  
# Things to do

- Develop the intro to python 

- Get CS 101 syllabus

# Possible Assignments

python Chapter 1 Question 4

python Chapter 1 Question 6

Chapter 1 Question 3 Theoretical

python Chapter 2 Question 7 & Question 9

python Chapter 3 Question 1,2,7,11

python Capter 4 Question 3,4,5,8

Note 4.3: It's previously worked out, graph and calculate the changes over time. Graph before the change, graph after the change. 

Note 4.4: Program it dynamically, do not hardcode alpha. 

